# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bram_sys_system_ila_1_0.xci
# IP: The module: 'bram_sys_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/bd_5560.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560 || ORIG_REF_NAME==bd_5560} -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_0/bd_5560_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560_ila_lib_0 || ORIG_REF_NAME==bd_5560_ila_lib_0} -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_1/bd_5560_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560_g_inst_0 || ORIG_REF_NAME==bd_5560_g_inst_0} -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_2/bd_5560_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560_slot_0_aw_0 || ORIG_REF_NAME==bd_5560_slot_0_aw_0} -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_3/bd_5560_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560_slot_0_w_0 || ORIG_REF_NAME==bd_5560_slot_0_w_0} -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_4/bd_5560_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560_slot_0_b_0 || ORIG_REF_NAME==bd_5560_slot_0_b_0} -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_5/bd_5560_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560_slot_0_ar_0 || ORIG_REF_NAME==bd_5560_slot_0_ar_0} -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_6/bd_5560_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560_slot_0_r_0 || ORIG_REF_NAME==bd_5560_slot_0_r_0} -quiet] -quiet

# XDC: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5560_ila_lib_0 || ORIG_REF_NAME==bd_5560_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5560_ila_lib_0 || ORIG_REF_NAME==bd_5560_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_0/bd_5560_ila_lib_0_ooc.xdc

# XDC: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/bd_5560_ooc.xdc

# XDC: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bram_sys_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_sys_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bram_sys_system_ila_1_0.xci
# IP: The module: 'bram_sys_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/bd_5560.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560 || ORIG_REF_NAME==bd_5560} -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_0/bd_5560_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560_ila_lib_0 || ORIG_REF_NAME==bd_5560_ila_lib_0} -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_1/bd_5560_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560_g_inst_0 || ORIG_REF_NAME==bd_5560_g_inst_0} -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_2/bd_5560_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560_slot_0_aw_0 || ORIG_REF_NAME==bd_5560_slot_0_aw_0} -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_3/bd_5560_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560_slot_0_w_0 || ORIG_REF_NAME==bd_5560_slot_0_w_0} -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_4/bd_5560_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560_slot_0_b_0 || ORIG_REF_NAME==bd_5560_slot_0_b_0} -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_5/bd_5560_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560_slot_0_ar_0 || ORIG_REF_NAME==bd_5560_slot_0_ar_0} -quiet] -quiet

# IP: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_6/bd_5560_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5560_slot_0_r_0 || ORIG_REF_NAME==bd_5560_slot_0_r_0} -quiet] -quiet

# XDC: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5560_ila_lib_0 || ORIG_REF_NAME==bd_5560_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5560_ila_lib_0 || ORIG_REF_NAME==bd_5560_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/ip/ip_0/bd_5560_ila_lib_0_ooc.xdc

# XDC: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bd_0/bd_5560_ooc.xdc

# XDC: /home/sanjayr/projects/U250/RTL_KERNEL_STREAMING_MSFT/t4_RTL_KER_immedeate_DONE_AXIL_FIFO_SW_START_STOP_SYS_ILA/test1/rtl_vadd_2clks/src/ip/bd/bram_sys/ip/bram_sys_system_ila_1_0/bram_sys_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_sys_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
